version: 0.3

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd UploadsNotificationFunction
      - VERSION=$(grep "projectVersion" gradle.properties | awk -F'=' '{print $2}' | tr -d ' ')
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo "Project Version -> $VERSION"
  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --s3-bucket volhakrypulevichbucket --template-file template.yml --output-template-file outputTemplate.yml
      - mv outputTemplate.yml ../outputTemplate.yml
artifacts:
  files:
    - outputTemplate.yml
